### PR TITLE
Feat/container issue11

### LINKED ISSUE #11: Mock API responses

### PR DESCRIPTION
**Pull request by michquinn**
There is a mongosh script which generates the test data file, but that step isn't part of the build process yet. Other than that, it works.

Would close #11

### CODE REVIEW

**Review by jkluse — COMMENTED** [review]
I reviewed but don't completely understand everything here. However, I'm looking forward to testing the API responses.

**Review by FlatBallFlyer — CHANGES_REQUESTED** [review]
I'm not sure I understand why are you loading test data. The database has test data pre-loaded for this purpose. If the data that is pre-loaded does not meet your requirements then please improve the test data that is loaded.

**Comment by michquinn** [comment]
The API returns objects which are the result of joining across collections. Improving the test data has nothing to do with that. There is a script which outputs the query results to a file for the mock container to use. Otherwise, it would need a database connection, which I haven't implemented yet (that's what the mock is there for)

**Review by FlatBallFlyer — APPROVED** [review]
I see how this is working, sorry for the confusion

**Pull request closed without merging**
