### PR TITLE
Feat/spec issue5

### LINKED ISSUE #5: Update spec for paths collection
- [ ] #6
- [ ] #7

### PR DESCRIPTION
**Pull request by michquinn**
Would close #5

### CODE REVIEW

**Review by FlatBallFlyer — CHANGES_REQUESTED** [review]
- [x] the endpoint  ``/api/topic/{id}/resource/{name}`` should be  ``/api/topic/{id}/resource/{id}``
- [ ] I think we need POST/GET/PATCH/DELETE endpoints for ``/api/topic/skills/``
- [x] the endpoint ``/api/path/{pathname}`` should be ``/api/path/{id}``
- [x] we need a GET ``/api/path/`` endpoint to get a list of paths
- [ ] we need a POST ``/api/path endpoint``
- [ ] we might need POST/PATCH/DELETE endpoints for ``/api/path/{id}/segment`` - we should discuss with John to see if that will make the UI easier to write. 

The schema does not appear to match the DB - maybe I'm reading it wrong but you used capitalization in property names that do not reflect the DB schema, and you seem to have duplicated topic.skills in resource.skills - in Resources the skills is a string[] not an object[].

**Comment by michquinn** [comment]
> maybe I'm reading it wrong but you used capitalization in property names that do not reflect the DB schema

I'll fix that

> and you seem to have duplicated topic.skills in resource.skills - in Resources the skills is a string[] not an object[].

From [Topic](https://github.com/agile-learning-institute/mentorHub-mongodb/blob/cac3b240eae7788a9ca768c47668424b62560e5f/src/mongosh/schemas/topics-2.0.3.json#L36-L42)

```json
                "skills": {
                        "description": "The list of skills related to this topic",
                        "bsonType": "array",
                        "items": {
                                "bsonType": "objectId"
                        }
                },
```
https://github.com/agile-learning-institute/mentorHub-topic-api/blob/6975f7e94bc11503eac638b9be9bb83ae4a27219/docs/openapi.yaml#L191-L194

From [Resources](https://github.com/agile-learning-institute/mentorHub-mongodb/blob/cac3b240eae7788a9ca768c47668424b62560e5f/src/mongosh/schemas/resources-1.0.3.json#L45-L51)

```json
                "skills": {
                        "description": "The list of skills this resource contributes to",
                        "bsonType": "array",
                        "items": {
                                "bsonType": "objectId"
                        }
                },
```
https://github.com/agile-learning-institute/mentorHub-topic-api/blob/6975f7e94bc11503eac638b9be9bb83ae4a27219/docs/openapi.yaml#L231-L234

I'm not sure where the disconnect is?

Sample output from the swagger editor
```json
{
  "Id": "string",
  "Name": "string",
  "Status": "Active",
  "Description": "string",
  "Category": "Foundations of ITSM",
  "Skills": [
    {
      "Name": "string",
      "Status": "Active",
      "Description": "string",
      "Mastery": "Candidate",
      "Speciality": "Generalist"
    }
  ],
  "Resources": [
    {
      "Name": "string",
      "Status": "Active",
      "Description": "string",
      "Duration": 2880,
      "Link": "https://5SKOODwl7ThyO303HnDFFxFhZxTKPsh3RgUazcF35y5NuieF7pkl6sshW.-LmWoRnWh7V3VSRJIBwdsfA.kTkZTW6BM2DsaT0wt2bexydpWj2U1Hwxbk-pWUAmkWIHStn-DmdyCcKu.61JBfQ3F5TFWxDbzl0zzidRTSZAI1cF9jO6D.K9.b7NMP8Pifq1AL7lSG8qn7CjoCeFptQIl6aC7ULOPpuuEU3w-yVB.3tqwUcF9WLS-84HEy",
      "Skills": [
        {
          "Name": "string",
          "Status": "Active",
          "Description": "string",
          "Mastery": "Candidate",
          "Speciality": "Generalist"
        }
      ],
      "Tags": [
        "$"
      ]
    }
  ]
}
```

**Comment by michquinn** [comment]
> we need a GET `/api/path/` endpoint to get a list of paths

Just names and IDs like with GET `/api/topic` or full path objects?

**Comment by michquinn** [comment]
> * I think we need POST/GET/PATCH/DELETE endpoints for `/api/topic/skills/`

I made this a separate [issue](#10)

**Review by FlatBallFlyer — APPROVED** [review]

**Pull request merged**
